### ISSUE TITLE
react-native run-android error - debug.keystore not found for signing config ‘debug’.

### ISSUE THREAD

**Issue by Luis16287** [EkaanshArora/Agora-React-Native-Demo#7]
I am having this error:
`PS E:\Proyectos\agora.io\Agora-React-Native-Demo> react-native run-android
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
– react-native-agora (to unlink run: “react-native unlink react-native-agora”)
– react-native-vector-icons (to unlink run: “react-native unlink react-native-vector-icons”)
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via “react-native unlink ” and it will be included in your app automatically. If a library isn’t compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using “–no-jetifier” flag.
(node:14520) Warning: Accessing non-existent property ‘padLevels’ of module exports inside circular dependency
(Use `node –trace-warnings …` to show where the warning was created)
Jetifier found 899 file(s) to forward-jetify. Using 4 workers…
info Starting JS server…
info Installing the app…
> Task :app:validateSigningDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use ‘–warning-mode all’ to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
43 actionable tasks: 3 executed, 40 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ‘:app:validateSigningDebug’.
> Keystore file ‘E:\Proyectos\agora.io\Agora-React-Native-Demo\android\app\debug.keystore’ not found for signing config ‘debug’.

* Try:
Run with –stacktrace option to get the stack trace. Run with –info or –debug option to get more log output. Run with –scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with –verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ‘:app:validateSigningDebug’.
> Keystore file ‘E:\Proyectos\agora.io\Agora-React-Native-Demo\android\app\debug.keystore’ not found for signing config ‘debug’.

* Try:
Run with –stacktrace option to get the stack trace. Run with –info or –debug option to get more log output. Run with –scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

at checkExecSyncError (child_process.js:611:11)
at execFileSync (child_process.js:629:15)
at runOnAllDevices (E:\Proyectos\agora.io\Agora-React-Native-Demo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
at buildAndRun (E:\Proyectos\agora.io\Agora-React-Native-Demo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
at E:\Proyectos\agora.io\Agora-React-Native-Demo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Command.handleAction (E:\Proyectos\agora.io\Agora-React-Native-Demo\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)`

**Comment by EkaanshArora** [comment]
Looks like you don't have a debug keystore set up. Try to generate it by running this command in android/app/
```
keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
```
